services:
  db:
    image: postgres:16-alpine
    container_name: funds-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: funds_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  db-test:
    image: postgres:16-alpine
    container_name: funds-db-test
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: funds_test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  pgdata:
